### ISSUE TITLE
error in run mon2cam after install

### ISSUE THREAD

**Issue by ratacheski** [ShayBox/Mon2Cam#47]
Hi, I installed it according to the instructions, but when I run mon2cam, it gives the error bellow.

```
error: TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { LoggerOptions } from "./logging.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/libraries/options.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Logger } from "./logging.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/libraries/utility.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import Options from "../libraries/options.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/backends/audio.ts:3:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Logger } from "../libraries/logging.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/backends/wayland.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import Options from "../libraries/options.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/backends/wayland.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import Options from "../libraries/options.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/backends/x11.ts:4:1
```

Deno Version:
deno 1.4.0
v8 8.7.75
typescript 4.0.2

Distro: PopOS 20.04 (Kernel 5.4.0-7642-generic)

**Comment by ShayBox** [comment]
Deno v1.4.0 enabled importsNotUsedAsValues by default

**Comment by ratacheski** [comment]
Thanks. Deno downgrade was fixed this issue.

**Comment by ratacheski** [comment]
Thanks. Deno downgrade was fixed this issue.
