### ISSUE TITLE
TypeScript Errors

### ISSUE THREAD

**Issue by MaksymBe** [ShayBox/Mon2Cam#49]
mon2cam -v=log
error: TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { LoggerOptions } from "./logging.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/libraries/options.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Logger } from "./logging.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/libraries/utility.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import Options from "../libraries/options.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/backends/audio.ts:3:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { Logger } from "../libraries/logging.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/backends/wayland.ts:1:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import Options from "../libraries/options.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/backends/wayland.ts:2:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import Options from "../libraries/options.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/backends/x11.ts:4:1

Found 6 errors.

Am I doing anything wrong? I'm just getting TS errors when trying to run mon2cam for the first time after installation.

**Comment by MaksymBe** [comment]
Issue was related to Deno, it just needs --no-check argument

**Comment by ShayBox** [comment]
I'll just fix the code in a bit
