### ISSUE TITLE
Permissions Error

### ISSUE THREAD

**Issue by AeronFA** [ShayBox/Mon2Cam#67]
Hello, my name is aeron i have tried to use you're application but when installing i seem to find a error, i am on a administrator ubuntu (20.04), and i have all the latest dependencies which were needed, but when i run mon2cam i get a permissions error (error: Uncaught PermissionDenied: Permission denied (os error 13)), Any reason why?

**Comment by ashtton** [comment]
Running into the same problem.

**Comment by AntoninJcb** [comment]
Same issue. Here is the stack trace:
```bash
✗(908ms) antonin:/tmp$ mon2cam
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
error: Uncaught PermissionDenied: Permission denied (os error 13)
at processResponse (core.js:226:13)
at Object.jsonOpSync (core.js:250:12)
at opRun (deno:cli/rt/40_process.js:19:17)
at Object.run (deno:cli/rt/40_process.js:103:17)
at exec (exec.ts:60:15)
at mod.ts:22:20
at async mod.ts:15:1
```
Looks like an issue with deno. I've installed it via snap.

**Comment by ShayBox** [comment]
Don't use the snap

**Comment by AntoninJcb** [comment]
> Don't use the snap

Indeed, this solved the issue for me. I've reinstalled deno through the command stated on the README link.

**Comment by ashtton** [comment]
> Don't use the snap

Fixed my issue.
